### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-advanced-css-selectors#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://overt-structure.surge.sh).

I was able to use nth child to differentiate odd and even rows, and empty to hid the empty cell, but they are causing a conflict with each other. How would I hide the empty cell and not have it count as a child? [Is it even possible with CSS?](http://stackoverflow.com/questions/31181430/selecting-nth-child-skipping-hidden-elements)

**Comment by chrisvfritz** [comment]
Looks great! :shipit: There's no way around that limitation that I know of, unfortunately. I actually included those two requirements together so that you would discover this. :wink: You _could_ solve the problem with JavaScript and the jQuery library though, which there's another lesson on later.

In your case, the following line of code could simply remove any `tr`s with an empty `td` from the page.

``` js
$('td:empty').parent('tr').remove()
```

**Comment by KatieMFritz** [comment]
Jerk.

**Comment by chrisvfritz** [comment]
:stuck_out_tongue:
